[project]
name = "unpreprocess"
dynamic = ["version"]
requires-python = ">=3.14"
readme = "README.md"
license-files = [
    "LICENSE",
]

dependencies = [
    "click>=8.5.0",
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "mypy>=2.4.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.10",
    "uv-dynamic-versioning>=0.14.1",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

# https://github.com/dependabot/dependabot-core/issues/12340
[tool.hatch.version.raw-options]
fallback_version = "0.0.0-unknown"

[tool.hatch.build.hooks.version]
path = "src/unpreprocess/_version.py"
